pysal/splot

splot/mapping.py

This PR proposes a fix for the behaviour reported in [`pysal#930`](https://github.com/pysal/pysal/issues/930). Additionally, it replaces `iteritems` for `items` when looping over `OrderedDict` objects, which makes it automatically Python 2 and 3 compatible (albeit less efficient in Python 2).

Fix for Pysal#930

---

MANIFEST.in
setup.py

- changed the version number to remove a warning
- removed 2to3 build command that is no longer needed
- added "splot" to package list so files in the package are included when installing with pip.
The problem here (https://github.com/pysal/esda/pull/19) was that only dummy files got installed:
```
(master) $ python setup.py sdist
/Users/steffie/anaconda3/envs/gsoc/lib/python3.6/site-packages/setuptools/dist.py:388: UserWarning: Normalizing '1.0.0dev' to '1.0.0.dev0'
normalized_version,
running sdist
running egg_info
creating splot.egg-info
writing splot.egg-info/PKG-INFO
writing dependency_links to splot.egg-info/dependency_links.txt
writing requirements to splot.egg-info/requires.txt
writing top-level names to splot.egg-info/top_level.txt
writing manifest file …
```

fix setup.py so files are installed with "pip install ."

---

setup.py

added `matplotlib` and `seaborn` to install requirements
to fix this issue: https://github.com/pysal/esda/pull/19
and this one: https://github.com/pysal/giddy/pull/47

add `seaborn` and `matplotlib` to `install_requirements` in `setup.py`

---

doc/conf.py
splot/_viz_esda_mpl.py

`moran_facet` plot was not showing in current documentation example
* changed outdated `f.by_col[vars]` to `f[vars]` in example
* commented out `static_` in config file to silence warning during doc build

fix current documentation for sprint

---

splot/_viz_libpysal_mpl.py
splot/tests/test_viz_libpysal_mpl.py

This PR is related to https://github.com/pysal/libpysal/issues/123 regarding the faster plotting of spatial weights for a large data set. The current [plot_spatial_weights function in splot](https://github.com/pysal/splot/blob/master/splot/_viz_libpysal_mpl.py#L15) seems to be essentially the same as the [plot method for W in libpysal](https://github.com/pysal/libpysal/blob/master/libpysal/weights/weights.py#L1201), both of which take a long time for a large data set. 
An example is given in [this notebook](https://gist.github.com/weikang9009/503be3a551c84d92f25f26425b461785) which tries to visualize the queen weight for a data set containing 4109 polygons. The implementations in splot and libpysal cost about 500 seconds while the updated implementation costs about 3 seconds.

(ENH) speed up plot_spatial_weights for plotting spatial weights

---

.travis.yml
README.md

Explicitly specify `Miniconda3` in .`travis.yml`.
pysal/giddy#82
pysal/giddy#83

update archaic Miniconda build

---

requirements_dev.txt

add `sphinxcontrib-bibtex` and `numpydoc` to `requirements_dev.txt`

migrating to readthedocs II

---

splot/_viz_esda_mpl.py
splot/_viz_utils.py
splot/tests/test_viz_esda_mpl.py
splot/tests/test_viz_giddy_mpl.py
splot/tests/test_viz_libpysal_mpl.py
splot/tests/test_viz_utils.py

* add `test_viz_utils.py` with `test_truncate_colormap()` and `test_shift_colormap()`
* add tests for ValueError and Warning in `test_viz_giddy_mpl.py` and `test_viz-esda_mpl.py`
* pep8 fixes
* add warning to `_moran_loc_bv-scatterplot()`
* add option to input a str in `truncate_colormap()`

Add tests for warnings and ValueErrors

---

doc/_static/pysal-styles.css
readthedocs.yml

migrate from readthedocs configuration file v1 to v2
docs building is successful on [my fork](https://readthedocs.org/projects/splot-wei/builds/9088586/)

docs building using readthedocs.yml version 2

---

.travis.yml
requirements_dev.txt

This PR is to set up dual travis tests for pysal dependencies (on pip and github):
* libpysal
* mapclassify
* esda
* giddy
* spreg
[The tests against github version are failing](https://travis-ci.org/weikang9009/splot) because of [the API change to mapclassify](https://github.com/pysal/splot/issues/65).

set up dual travis tests for pysal dependencies (pip and github) 

---

splot/_viz_utils.py

avoids wrong colours if certain values not present as addressed in #72 and https://github.com/pysal/pysal/issues/1101

[ENH] select colour by presence of value in list in `mask_local_auto`

---

requirements.txt

due to change in geopandas API

add descartes to `requirements.txt`

---

requirements.txt

add `,<=0.6.0rc1` in `requirements.txt` to allow testing on travis
Note: this is a work-around solution, the bug will be addressed in cooperation with GeoPandas team

[BUG] require geopandas>=0.4.0,<=0.6.0rc1 for vba_choropleth testing

---

README.md

Change splot doc badge to latest version instead of stable version for JOSS submission.
For some reason the stable version points to the old pysal documentation.

[ENH] change doc badge to latest doc

---

splot/_viz_libpysal_mpl.py

I noticed a minor issue with `plot_spatial_weights` docstring as it uses `Arguments` instead of `Parameters`, so it is not visible in [docs](https://splot.readthedocs.io/en/latest/generated/splot.libpysal.plot_spatial_weights.html#splot.libpysal.plot_spatial_weights).
Just a side note, this second point in your PR template is no longer valid, right?  `pysal/dev` is way behind master.
> 2. [ ] This pull request is directed to the `pysal/dev` branch.
cc https://github.com/openjournals/joss-reviews/issues/1882

Fix docstring for plot_spatial_weights

---

splot/_viz_utils.py
splot/_viz_value_by_alpha_mpl.py

[mapclassify 2.2.0](https://github.com/pysal/mapclassify/releases/tag/v2.2.0) removed deprecated class names.

BUG: Fix breakage due to mapclassify deprecation

---

README.md
doc/installation.rst
paper/paper.md

This PR builds on top of #96 and addresses #90 and #92 
* add figure captions in `paper.md` through markdown italics formatting
* add links of notebook examples and other material to `README.md` under `Usage` section
* add script lightning talk as documentation under introduction in `README.md`

[DOC] add example links to README.md & figure captions in joss article

---

paper/paper.md

Include the links in the figure caption instead to avoid issues when compiling the paper PDF.
You can preview the compiled paper at: http://res.cloudinary.com/hju22ue2k/image/upload/v1580414535/wvsuqwnyi5rgshtoru7i.pdf
The "Figure 1" etc are added automatically when compiling the paper. I used the link to the master branch notebook but this is probably not ideal since that link will break if the notebooks are moved. It would be best to link to the specific version used in the JOSS paper (feel free to update this branch).
openjournals/joss-reviews#1882
1. [ ] You have run tests on this submission, either by using [Travis Continuous Integration testing](https://github.com/pysal/pysal/wiki/GitHub-Standard-Operating-Procedures#automated-testing-w-travis-ci) testing or running `nosetests` on …

Remove the links around figures in the JOSS paper

---

CHANGELOG.md
setup.py
splot/__init__.py

Version 1.1.3 (2020-03-18)
We closed a total of 15 issues (enhancements and bug fixes) through 6 pull requests, since our last release on 2020-01-18.
- add permanent links to current version of no's to joss paper (#102)
- [BUG] set colors as list in _plot_choropleth_fig() (#101)
- Remove the links around figures in the JOSS paper (#99)
- Release prep for 1.1.2 (#98)
- Installation instructions; pip install fails on macOS (#88)
- Usage in readme is a fragment (#90)
- JOSS: missing figure captions (#92)
- [DOC] update installation instruction (#96)
- [DOC] add example links to README.md & figure captions in joss article (#97)
- add permanent links to current version of no's to joss paper (#102)
- [BUG] set colors as list in _plot_choropleth_fig() (#101)
- Remove the links around figures in …

Release1.1.3

---

splot/_viz_giddy_mpl.py
splot/tests/test_viz_esda_mpl.py

* update links to test datasets according to new libpysal api in `_test_viz_esda_mpl()`
* enforce to either pass `c` or `color` to `lines = ax.plot()` in `dynamic_lisa_vectors()`, not both if c is added by user as a kwargs argument. This adopts a deprecation warning: new error when both c and color are defined, implemented with matplotlib 3.3.
addresses #116 and  #117

[MAINT] update links to Guerry dataset in `_test_data()`

---

.travis.yml
splot/_viz_esda_mpl.py
splot/tests/test_viz_esda_mpl.py

splot build failing on `plot_local_autocorrelation()` for python v 3.7 due to change in behaviour in `pandas.DataFrame.isin()`.
For more information see #123.
* added functionality that converts values in `mask` to same type as values in `region_column`
* added warning that mask type and `region_column` type are not the same
* raising ValueError if specified values in `mask` not in the dataset
* add test to check ValueError is raised
* added comment in documentation
* Added Columbus dataset to travis.yml

[BUG] enforce dtype in `mask` in `plot_local_autocorrelation()`

---

setup.py

* adds missing commas to `setup.py`

[MAINT] add missing comma in `setup.py`

---

splot/_viz_value_by_alpha_mpl.py

The justification for this PR is: 
Importing ABC from `collections` was deprecated since Python 3.4 and removed in Python 3.10 . Use `collections.abc` instead.

Import ABC from collections.abc for Python 3.10 compatibility.

---

doc/conf.py

RTD build fails as we haven't updated `conf.py` to work with newer versions of `sphinxcontrib.bibtex`. This should fix it.

DOC: update docs for bibtex>1

---

.github/release.yml
.github/workflows/release_and_publish.yml

add GHA for release

---

.github/workflows/release_and_publish.yml

This PR removes the manual trigger from `release_and_publish.yml`.

remove manual trigger
