splot/plot.py, splot/tests/test_plot.py
adding option to visualise plot according to significance (HH, LL, HL, LH):
allowing for input from both Moran and Moran_Local
adding test to test if both options work
=> add visualization option with significance to mplot

doc/conf.py, doc/index.rst, doc/libpysal.rst, splot/_viz_esda_mpl.py, splot/_viz_giddy_mpl.py, splot/_viz_libpysal_mpl.py, splot/esda.py, splot/libpysal.py
debug doc-strings in `._viz_esda_mpl.py`
add `autosummary_generate = True` in `config.py`
=> debug `splot` documentation

README.md
Very minor correction in `README.md`
=> adjusting markdown font

requirements_dev.txt
add `shpinx_bootstrap_theme` to `requirements_dev.txt` install
=> migration to readthedocs

paper/paper.md
* create paper directory
* add 'paper.md' template
* add 'paper.bib' template
in order to kick start JOSS submission
note this builds on top of #56
=> create paper directory

.travis.yml
[Travis CI testing is passing on my fork](https://travis-ci.org/weikang9009/splot/jobs/533994317)
=> travis ci testing: migrate from 3.5 and 3.6 to 3.6 and 3.7

requirements_dev.txt
=> add ipywidgets to requirements_dev.txt

CHANGELOG.md, setup.py, splot/__init__.py, tools/gitcount.ipynb
change release number to 1.1.1
* `__init__.py`
* `setup.py`
add release notes to `CHANGELOG.md`
=> Release 1.1.1

paper/paper.md
* finalise paper format and change title to fit one line
=> Joss paper, finalise title

.travis.yml, splot/tests/test_viz_esda_mpl.py, splot/tests/test_viz_libpysal_mpl.py
* addressing the travis dual testing problem raised in pysal/pysal#1145
* adapting tests to libpysal v4.2 examples schema
=> addressing pysal/pysal#1145 & adapting testing examples

doc/installation.rst
Update of installation instructions in documentation
* adding information about dependencies
* informing users of ways of trouble shooting
* including conda-forge installation instructions
addresses #88
=> [DOC] update installation instruction

CHANGELOG.md, requirements.txt, setup.py, splot/__init__.py, tools/gitcount.ipynb
* remove geopandas restrictions from `requirements.txt` due to newest geopandas release
* change version nr to 1.1.2 in `__init__.py` and `setup.py`
* add release notes to `CHANGELOG.md`
=> Release prep for 1.1.2

splot/_viz_bokeh.py
Bug due to recent change of Bokeh functionality in bokeh.palettes
convert palettes tuple to list to solve AttributeError
=> [BUG] set colors as list in _plot_choropleth_fig()

paper/paper.md, splot/_viz_bokeh.py
following reviewers recommendation
build on top of #101
=> add permanent links to current version of no's to joss paper

paper/paper.bib
add suggested references and fix incorrect doc
https://github.com/openjournals/joss-reviews/issues/1882
=> [JOSS] doi reference correction

README.md
* adds joss doc badge to readme
We just published a Joss paper together 🎉
=> [JOSS] add Joss badge to README.md

README.md, doc/index.rst
Fixing links in the docs. The point to 404 now.
=> DOC: change links from master to main

CHANGELOG.md
Adding a manual changelog before we figure out the best way to deal with it.
=> [RLS] changelog for 1.1.5

.github/workflows/unittests.yml, ci/310-DEV.yaml, ci/310-DEV_shapely_dev.yaml, ci/310.yaml, ci/38.yaml, ci/39.yaml, requirements.txt, splot/_viz_esda_mpl.py
This PR:
* updates the `mapclassify` and `spreg` branches to `main` in CI due to [failures](https://github.com/pysal/splot/actions/runs/3365988409/jobs/5582023881#step:4:51)
* add testing against shapely dev (xref https://github.com/pysal/spopt/issues/291)
* resolves #160
=> update dev branches; test shapely dev

.github/workflows/unittests.yml
`esda` default branch in now `main`.
=> default esda branch master -> main

README.md
This PR
* resolves #189 
* xref #188
=> add note to README about archival process
